version: '2.1'

services:
  vikings:
    image: vikings
    build: .
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 7626:8626
    command: npm run start_azure_debug
